language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libgtkmm-3.0-dev 
    - libxml2-utils

before_script:
  - mkdir build
  - cd build
  - cmake ..

#script: make && make test
script: make