dist: xenial
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - libgtkmm-3.0-dev 
    - libxml2-utils
    - gcc-7
    - g++-7

before_script:
  - mkdir build
  - cd build
  - cmake ..

#script: make && make test
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-7
  - export CXX=g++-7
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - make